H4ppy-04/urban-cli

src/urban.py
tests/test_urban.py

- Modularization into separate functions for unit tests.
- Additional type checking and type safety.
- Preventative measures when lists and things won't have values.
- Redundancy warnings.
**Issues**: closes #3
**Tag**: 1.0.2

feat: refactors, type safety, tests

---

src/urban.py

- Addresses issue where response codes were very generic (see attached issue)
> Response codes are still pretty generic however, they have been tested, they do work.

handle request response code ranges from 100 to 599

---

src/urban.py

**About**
This commit now shows the author with the definition.
Attempted to add function to get likes and dislikes however they are rendered via javascript post-load so that's impossible 👽
Issue: #2
---
> **Note:** Need to remove deprecation warning showing due to the usage of a deprecated function.

feat: show author with definition

---

src/urban.py

- Issue: #11
- Authored-by: Joshua Rose <joshuarose099@gmail.com>

fix: space issue. easiest fix of my life holy shit

---

.github/workflows/python-app.yml

- adds default actions template with pytest and requirements checking.

feat: add github actions testing

---

requirements.txt

add dependencies for github actions

chore: add dependencies

---

requirements.txt

Adds parser library lxml as dependency to move along gh actions

chore: add parser library as dependency

---

.github/labeler.yml
.github/workflows/label.yml

> fuck it - we ball.
failing ci (needing to add `labeler.yml`)

feat(ci): add failing CI

---

.github/labeler.yml
.github/release-drafter.yml
.github/workflows/release-drafter.yml

This commit adds a default release drafter config. Labels have been cusomized to fit the repository.
Issue: #18

feat: initial commit for release drafter

---

src/urban.py

fix: modifications to index algorithm

---

install.sh

* Checks before using log folder
* Creates log folder if doesn't exist
* Created as function

checks for log folder in installation if it doesn't already exist

---

src/urban.py
tests/test_definition.py
tests/test_unit_integration.py

* Removes redundant test stubs
* Removes non-covered tests
* Deletes unused imports

remove redundant stubbing in `urban.py` and non-covered tests

---

tests/test_unit_integration.py

Revert "remove redundant test scaffolding"

---

CODE_OF_CONDUCT.md

* copy paste template
* email stuff

feat(docs): adds `CODE_OF_CONDUCT.md` template

---

CONTRIBUTING.md

* Copy paste contributing from existing contributing document on wiki

Import contributing from existing docs/wiki

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

* Add bug report template (custom)
* Add feature request (custom)

Add bug and feature form for reporting new issues and suggesting new features

---

SECURITY.md

* Create non-implementable stub file for security / contribution

add `SECURITY.md` stub file for GitHub contributions

---

TODO.md
docs/source/about.md

* add emojis instead of text
* add legend for emojis
* add different tables depending on the release
* shortened a few things

refactor release table to sort via releases 

---

TODO.md
docs/source/about.md
docs/source/index.rst
docs/source/releases.md

- feat(todo): add todo
- feat: add note about contributing
- refactor(docs): refactored release table
- refactor(docs): seperate release page

separate release page on wiki

---

urban/urban_utils.py

* wotd functionality returns dictionary class
* refactors original definition class
* makes a few functions redundant
- refs: resolves the #56 issue

word of the day functionality returns `Dictionary` class

---

docs/source/conf.py
urban/__main__.py

Fixes definition object error.
Resolves #63

fix: Fix definition object issue

---

urban/__main__.py
urban/urban_api.py

This commit fixes the #67 error.
Issue: #67

fix: `NameError` bug for multiple params on input

---

urban/__main__.py
urban/urban_api.py

Revert "fix: `NameError` bug for multiple params on input"

---

urban/__main__.py
urban/urban_api.py
urban/urban_commands.py
urban/urban_definition.py

* Fix `--result` functionality
* Fix `--order` warnings

fix: Fix `--result` functionality and `--order` logger warnings

---

urban/urban_utils.py

- *fixes* instance check, closes #78
- *adds* paragraph spacing #75

instance check fix, feat spacing features

---

docs/source/index.rst

Removed a redundant notice from the documentation

moved redundant notice from docs

---

README.md
scripts/venv.sh

feat: Issues/88 - add venv script

---

.github/workflows/sphinx.yml
pyproject.toml

Current thing is broken. needs fix.

[TEST] build test for 'Publish github pages'

---

.github/workflows/sphinx.yml
pyproject.toml
src/urban/definition.py
src/urban/parser.py
src/urban/request.py

- **build test**
- **test: [modify regex] add additional branches to sphinx**
- **add workflow dispach**
- **chore(format): black, isort**

[FORMAT] ran formatters
